DROP SEQUENCE sc_result;
DROP SEQUENCE sc_reference_value;
DROP SEQUENCE sc_result_factor;
DROP SEQUENCE sc_assembly_test;
DROP SEQUENCE sc_assembly;
DROP SEQUENCE sc_assembly_descriptor;
DROP SEQUENCE sc_test;
DROP SEQUENCE sc_test_description;
DROP SEQUENCE sc_assembly_type;
DROP SEQUENCE sc_lab_area;
DROP SEQUENCE sc_sample_type;
DROP SEQUENCE sc_labcase;
DROP SEQUENCE sc_animal;
DROP SEQUENCE sc_race;
DROP SEQUENCE sc_specie;
DROP SEQUENCE sc_enterprise;
DROP SEQUENCE sc_place;
DROP SEQUENCE sc_place_type;
DROP SEQUENCE sc_assembly_control;
DROP SEQUENCE sc_prices_by_test_desc;
DROP SEQUENCE sc_bill_detail;
DROP SEQUENCE sc_bill;
DROP SEQUENCE sc_test_profile;
DROP SEQUENCE sc_profile;
DROP TABLE result CASCADE;
DROP TABLE reference_value CASCADE;
DROP TABLE result_factor CASCADE;
DROP TABLE assembly_test CASCADE;
DROP TABLE assembly CASCADE;
DROP TABLE assembly_descriptor CASCADE;
DROP TABLE test CASCADE;
DROP TABLE test_description CASCADE;
DROP TABLE assembly_type CASCADE;
DROP TABLE lab_area CASCADE;
DROP TABLE sample_type CASCADE;
DROP TABLE animal CASCADE;
DROP TABLE labcase CASCADE;
DROP TABLE race CASCADE;
DROP TABLE specie CASCADE;
DROP TABLE enterprise CASCADE;
DROP TABLE place CASCADE;
DROP TABLE place_type CASCADE;
DROP TABLE sections_roles CASCADE;
DROP TABLE sections CASCADE;
DROP TABLE user_roles CASCADE;
DROP TABLE roles CASCADE;
DROP TABLE users CASCADE;
DROP TABLE application_owner CASCADE;
DROP TABLE assembly_control CASCADE;
DROP TABLE authorization_codes CASCADE;
DROP TABLE bank_place CASCADE;
DROP TABLE lab_professional CASCADE;
DROP TABLE prices_by_test_desc CASCADE;
DROP TABLE sequential_numbers CASCADE;
DROP TABLE bill_detail;
DROP TABLE bill;
DROP TABLE test_description_profile;
DROP TABLE test_profile;
DROP TABLE profile;